Base:
  User: todoroki
  Keyfile: $KEYFILE
  Sudopass: $SUDOPASS
  Nodes:
    publisher-1:
      address: 10.20.22.158
    subscriber-1:
      address: 10.20.22.159
    broker-1:
      address: 10.20.22.161
    broker-2:
      address: 10.20.22.162
    broker-3:
      address: 10.20.22.163
    manager:
      address: 10.20.22.164
      is_manager: true

Systems:
  type: kafka
  Broker:
    zookeeper:
      containers:
        zoo-1:
          node_name: broker-1
          environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
      containers:
        kafka-1:
          node_name: broker-1
          environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9092
            KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        kafka-2:
          node_name: broker-2
          environment:
            KAFKA_BROKER_ID: 2
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9092
            KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        kafka-3:
          node_name: broker-3
          environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9092
            KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      topics:
          - "partition-3-1:3:1"
  Publisher:
    containers:
      pub-1:
        node: publisher-1
        broker: kafka-1:9092,kafka-2:9092,kafka-3:9092
        number: 3
        topic: "partition-3-1"
        messeage_size: 1k
        batch_size: 5
  Subscriber:
    containers:
      pub-1:
        node: suscriber-1
        broker: kafka-1:9092,kafka-2:9092,kafka-3:9092
        number: 1
        topic: "partition-3-1"
  duration: 5m

Actions:
  delay1:
    mode: delay
    time: 100ms
    source:
      - kafka-1
    destnation:
      - kafka-2
      - kafka-3
    start: 1m
    duration: 1m