version: '3.8'
services:
  zoo-1:
    image: confluentinc/cp-zookeeper:5.5.6
    hostname: zoo-1
    volumes:
    - type: bind
      source: /tmp/zoo-1/log
      target: /var/lib/zookeeper/log
    - type: bind
      source: /tmp/zoo-1/data
      target: /var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - kafka-network
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname==broker-1
  kafka-1:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-1
    volumes:
    - type: bind
      source: /tmp/kafka-1/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
    - kafka-network
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname==broker-1
  kafka-2:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-2
    volumes:
    - type: bind
      source: /tmp/kafka-2/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
    - kafka-network
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname==broker-2
  kafka-3:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-3
    volumes:
    - type: bind
      source: /tmp/kafka-3/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
    - kafka-network
    deploy:
      mode: global
      placement:
        constraints:
        - node.hostname==broker-3
networks:
  kafka-network:
    external: true
