version: '3.8'
services:
  delay1-0:
    image: gaiaadm/pumba
    hostname: delay1-0
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    networks:
    - kafka-network
    command: --json --log-level info netem -d 20s --tc-image gaiadocker/iproute2 --target
      10.0.1.109 --target 10.0.1.111 delay --time 100 --jitter 0 re2:.*kafka-3.*
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-3
      restart_policy:
        condition: on-failure
networks:
  kafka-network:
    external: true
