version: "3.8"

services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:5.5.6
    volumes:
      - type: bind
        source: /tmp/zoo-1/log
        target: /var/lib/zookeeper/log
      - type: bind
        source: /tmp/zoo-1/data
        target: /var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - kafka-cluster
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==broker-1"

  kafka1:
    hostname: kafka1
    image: confluentinc/cp-kafka:5.5.6
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /tmp/kafka-1/data
        target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:29092,OUTSIDE://10.20.22.160:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks: 
      - kafka-cluster
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==broker-1"

  kafka2:
    hostname: kafka2
    image: confluentinc/cp-kafka:5.5.6
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /tmp/kafka-2/data
        target: /var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:29092,OUTSIDE://10.20.22.161:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks: 
      - kafka-cluster
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==broker-2"

  kafka3:
    hostname: kafka3
    image: confluentinc/cp-kafka:5.5.6
    depends_on:
      - zookeeper
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /tmp/kafka-3/data
        target: /var/lib/kafka/data  
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:29092,OUTSIDE://10.20.22.162:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks: 
      - kafka-cluster
    deploy:
      mode: global
      placement:
        constraints:
          - "node.hostname==broker-3"

networks:
  kafka-cluster:
    external: true