version: '3.8'
services:
  zoo-1:
    image: confluentinc/cp-zookeeper:5.5.6
    hostname: zoo-1
    volumes:
    - type: bind
      source: /tmp/zoo-1/log
      target: /var/lib/zookeeper/log
    - type: bind
      source: /tmp/zoo-1/data
      target: /var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888
      ZOOKEEPER_SERVER_ID: 1
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-1
  zoo-2:
    image: confluentinc/cp-zookeeper:5.5.6
    hostname: zoo-2
    volumes:
    - type: bind
      source: /tmp/zoo-2/log
      target: /var/lib/zookeeper/log
    - type: bind
      source: /tmp/zoo-2/data
      target: /var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888
      ZOOKEEPER_SERVER_ID: 2
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-2
  zoo-3:
    image: confluentinc/cp-zookeeper:5.5.6
    hostname: zoo-3
    volumes:
    - type: bind
      source: /tmp/zoo-3/log
      target: /var/lib/zookeeper/log
    - type: bind
      source: /tmp/zoo-3/data
      target: /var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: zoo-1:2888:3888;zoo-2:2888:3888;zoo-3:2888:3888
      ZOOKEEPER_SERVER_ID: 3
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-3
  kafka-1:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-1
    volumes:
    - type: bind
      source: /tmp/kafka-1/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2181,zoo-3:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 256000
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 10485760
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9092
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-1
  kafka-2:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-2
    volumes:
    - type: bind
      source: /tmp/kafka-2/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2181,zoo-3:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 256000
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 10485760
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9092
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-2
  kafka-3:
    image: confluentinc/cp-kafka:5.5.6
    hostname: kafka-3
    volumes:
    - type: bind
      source: /tmp/kafka-3/data
      target: /var/lib/kafka/data
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zoo-1:2181,zoo-2:2181,zoo-3:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_REPLICA_LAG_TIME_MAX_MS: 30000
      KAFKA_MIN_INSYNC_REPLICAS: 3
      KAFKA_REPLICA_SOCKET_RECEIVE_BUFFER_BYTES: 256000
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 10485760
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 10485760
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9092
    networks:
    - kafka-network
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.hostname==broker-3
networks:
  kafka-network:
    external: true
